name: Lint

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: 'check --config ruff.toml'
      