name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    strategy:
      matrix:
        python: ['3.11']
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        make setup-dev
        make venv
        venv/bin/python3 -m pip install tox-gh-actions
      env:
        SLUGIFY_USES_TEXT_UNIDECODE: yes
    - name: Check formatting with black
      run: make fmt-check
    - name: Lint with pylint
      run: make lint
    - name: Test with tox
      run: make test

