name: Publish Packages
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  Publish:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install twine build
          python -m pip install keyrings.google-artifactregistry-auth
      - name: Make dists
        run: |
          python -m build
      - name: Show output
        run: tree .

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2.1.0'
        with:
            workload_identity_provider: projects/248644630671/locations/global/workloadIdentityPools/ganymede-core-dev-pool/providers/ganymede-core-dev-provider
            service_account: "py-upload@ganymede-core-dev.iam.gserviceaccount.com"
            create_credentials_file: true 
            export_environment_variables: true

      - name: Publish package
        run: |
          python3 -m twine upload --verbose --repository-url https://us-central1-python.pkg.dev/ganymede-core-dev/ganymede-py/ dist/*

# cant run in fork          
# jobs:
#   publish_package:
#     uses: Ganymede-Bio/common-gh-workflows/.github/workflows/publish-python-package.yaml@main
#     with:
#       GCP_PROJECT: ganymede-core-dev
#       WORKLOAD_IDENTITY_PROVIDER: projects/248644630671/locations/global/workloadIdentityPools/ganymede-core-dev-pool/providers/ganymede-core-dev-provider
#       WORKLOAD_IDENTITY_SERVICE_ACCOUNT: py-upload
