name: Publish Packages to Prod
on:
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install twine build
        python -m pip install keyrings.google-artifactregistry-auth
    - name: Make dists
      run: |
        python -m build
    - name: Show output
      run: tree .

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2.1.0'
      with:
          workload_identity_provider: projects/740903496187/locations/global/workloadIdentityPools/ganymede-core-pool/providers/ganymede-core-provider
          service_account: "py-upload@ganymede-core.iam.gserviceaccount.com"
          create_credentials_file: true 
          export_environment_variables: true

    - name: Publish package
      run: |
        python3 -m twine upload --verbose --repository-url https://us-central1-python.pkg.dev/ganymede-core/ganymede-py/ dist/*
